spring:
  application:
    name: aesp-backend
  server:
    port: 8080
    address: 0.0.0.0
  datasource:
    url: jdbc:mysql://localhost:3306/aesp
    username: root
    password: Dokhoa2005##
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    com.aesp_backend.aesp_backend: DEBUG

secure:
  #  cac url duoc security bo qua
  ignored:
    urls:
      - /admin/register
      - /admin/login
      - /user/register
      - /mentor/register
      - /mentor/login
      - /token/refresh-token
